from fastapi import FastAPI, HTTPException
import httpx

app = FastAPI()

# Define the base URLs for the different systems

systems = ["fire", "flooding", "earthquake", "burglary", "crime",  "safety", "health"]

@app.get("/api/v1/{category}")
async def get_data(category: str):
    if category not in systems:
        raise HTTPException(status_code=404, detail="System not found")

    if category == "fire":
        return {"data": "In the event of a fire, stay calm, alert others by shouting "Fire," and evacuate safely using designated escape routes, avoiding elevators and crawling low under smoke. If clothes catch fire, stop, drop, and roll. Call emergency services (e.g., 911, 999, or 119) and provide the exact address and nature of the fire. Notify local government or military hotlines for additional support. Use firefighting equipment like extinguishers or blankets only if the fire is small and it is safe to do so, and activate fire alarms to warn others. After evacuation, gather at designated meeting points, account for everyone, and report to emergency responders about missing persons or hazards. Do not re-enter the building until cleared by authorities. Key emergency contacts should include the fire department, police, ambulance, government emergency hotline, and, if applicable, military assistance lines. Preventive measures include participating in fire drills, learning fire prevention strategies through government campaigns, and collaborating with military forces for evacuation planning in high-risk zones."}
    
    if category == "flooding":
        return {"data": "In the event of flooding, stay calm, move to higher ground, and avoid walking or driving through floodwaters. Alert others in the area to the danger and follow evacuation orders issued by local authorities. Contact emergency services (e.g., 911, 999, or relevant local numbers) to report immediate dangers and provide your location. Notify government disaster management hotlines or military assistance lines if additional aid is needed. Turn off utilities such as gas, electricity, and water if it is safe to do so. Avoid contact with floodwater, as it may be contaminated, and do not attempt to cross fast-moving water. After evacuating, stay at designated safe areas or shelters, and monitor updates from local government or military agencies via emergency broadcasts or hotlines. Key contacts should include emergency services, government disaster response units, and, if applicable, military rescue teams. Preventative measures include participating in local flood preparedness programs, having an emergency kit ready, and knowing evacuation routes. Collaborate with local government and military teams for effective response and recovery planning."}
    
    if category == "earthquake":
        return {"data": "In the event of an earthquake, stay calm and act quickly. If indoors, drop to the ground, take cover under sturdy furniture, and hold on until shaking stops; avoid windows, heavy furniture, and external walls. If outdoors, move to an open area away from buildings, trees, and power lines. If in a vehicle, stop in a safe location, avoid overpasses, and remain inside. Alert others to danger and follow evacuation orders issued by authorities. After the shaking stops, check for injuries and hazards like gas leaks or fires, and turn off utilities if safe. Contact emergency services (e.g., 911, 999, or local numbers) to report injuries or major damage. Notify local government disaster management hotlines or military assistance lines for additional help. Avoid using elevators and damaged structures until declared safe by authorities. Key contacts should include emergency services, government disaster response units, and military aid lines. Preventative measures include earthquake drills, securing heavy items, and preparing emergency kits with essentials. Collaborate with government and military agencies for effective recovery planning and support."}
    
    if category == "burglary":
        return {"data": "In the event of a burglary, stay calm and prioritize safety. If you are inside and suspect a burglary is occurring, avoid confrontation, quietly secure yourself in a safe area, and call emergency services (e.g., 911, 999, or relevant local numbers) to report the incident. Provide details such as the location, description of suspects, and any visible weapons. If you are outside and notice signs of a burglary, do not enter; contact emergency services immediately. Notify local government authorities or police hotlines for follow-up assistance. Avoid touching anything in the crime scene to preserve evidence. If safe, alert neighbors or building security to increase awareness. After authorities arrive, provide a detailed account of the incident and list any stolen items. Key contacts should include police, insurance providers, and local neighborhood watch programs if available. Preventative measures include installing security systems, reinforcing doors and windows, and participating in government or community safety initiatives. Collaborate with law enforcement or military patrols in high-risk areas to enhance security."}
    
    if category == "crime":
        return {"data": "In the event of a crime, stay calm and prioritize personal safety. Avoid confrontation and move to a safe location if possible. Contact emergency services (e.g., 911, 999, or local emergency numbers) immediately to report the crime, providing details such as location, description of suspects, and any visible weapons. If you are a witness, observe discreetly and avoid intervening to ensure your safety. Notify local authorities or government hotlines for follow-up assistance and report any additional information. If in a high-risk area, inform military or security patrols if applicable. Preserve the scene by avoiding contact with potential evidence. After authorities arrive, cooperate fully by providing a detailed account of the incident. Key contacts should include police, victim support services, and local government authorities. Preventative measures include staying informed about local crime risks, participating in neighborhood safety programs, and following government or law enforcement guidelines for crime prevention. Collaborate with community or military safety initiatives to enhance security in vulnerable areas."}
    
    if category == "safety":
        return {"data": "To ensure safety, stay aware of your surroundings, follow government and local guidelines, and prepare for emergencies by keeping essential items like food, water, and first aid supplies readily available. Know key emergency contact numbers (e.g., 911 or local hotlines) and the locations of nearby police stations, hospitals, and shelters. At home, secure heavy objects, install smoke detectors, and have an evacuation plan; outdoors, avoid unsafe areas and follow traffic and safety rules. In workplaces, adhere to protocols and use protective equipment. Participate in community safety programs, such as neighborhood watch groups or emergency drills, and coordinate with local authorities or military teams if in high-risk zones. Always prioritize safety over possessions, and follow emergency personnel instructions in any situation."}
    
    if category == "health":
        return {"data": "In a health emergency, stay calm and act quickly to ensure safety. Call emergency services (e.g., 911, 999, or the local emergency number) and provide clear information about the situation, including symptoms, location, and medical history if known. If trained, administer first aid or CPR until help arrives, prioritizing actions such as stopping bleeding, performing rescue breaths, or stabilizing fractures. Avoid moving the individual unless necessary to prevent further harm. Notify family members or caregivers, and follow instructions from emergency responders or healthcare professionals. Keep a well-stocked first aid kit and know basic first aid techniques. Preventative measures include maintaining a healthy lifestyle, having regular medical check-ups, and keeping a list of emergency contacts, including family doctors and local health hotlines. Collaborate with community health programs and government initiatives to stay informed about local health risks and resources."}
